artifacts_root: artifacts

data_ingestion:
  AWS_REGION: us-east-1
  BUCKET_NAME: mental-health-dataset-capstone
  S3_OBJECT_KEY: mental_health_dataset.csv
  root_dir: artifacts/data_ingestion
  LOCAL_DOWNLOAD_FILE: artifacts/data_ingestion/mental_health_dataset.csv 

data_cleaning_encoding:
  input_file: artifacts/data_ingestion/mental_health_dataset.csv  # ✅ The ingested file is used as input
  output_file: artifacts/data_cleaning_encoded/cleaned_encoded_data.csv  # ✅ Save cleaned & encoded data here