artifacts_root: artifacts

data_ingestion:
  AWS_REGION: us-east-1
  BUCKET_NAME: mental-health-dataset-capstone
  S3_OBJECT_KEY: mental_health_dataset.csv
  root_dir: artifacts/data_ingestion
  LOCAL_DOWNLOAD_FILE: artifacts/data_ingestion/mental_health_dataset.csv 

data_cleaning_encoding:
  input_file: artifacts/data_ingestion/mental_health_dataset.csv
  output_file: artifacts/data_cleaning_encoded/cleaned_encoded_data.csv

model_training:
  input_file: artifacts/data_cleaning_encoded/cleaned_encoded_data.csv
  output_dir: artifacts/model_training
  target_columns:
    - Mental_Health_Condition_Yes  # Corrected column name
    - Severity
    - Stress_Level
  test_size: 0.2
  random_state: 42
  hyperparam_grids:
    LogisticRegression:
      C: [0.1, 1, 10]
    DecisionTree:
      max_depth: [null, 5]
      min_samples_split: [2, 5]
    SVC:
      C: [0.1, 1]
      kernel: [linear, rbf]
    RandomForest:
      n_estimators: [50, 100]
      max_depth: [null, 5]
    GradientBoosting:
      n_estimators: [50, 100]
      learning_rate: [0.01, 0.1]
    KNeighbors:
      n_neighbors: [3, 5]
      weights: [uniform, distance]
    NaiveBayes:
      var_smoothing: [1e-9, 1e-8]